(BKND) Socket Messaging - In progress
bounswe/bounswe2020group4 pull request #413
Opened 2021-01-12 20:22 UTC by koraycetiin

2021-01-14 17:20 UTC, multiminparvo requested changes
Please check the ip addresses in the nginx.conf file

2021-01-16 13:39 UTC, koraycetiin commented
> Please check the ip addresses in the nginx.conf file

done!

2021-01-16 14:55 UTC, eridincu commented on backend/interaction_service/models/message.js
> +module.exports.Message = mongoose.model(
Nice to have in future: I didn't see that in our requirements but the customer might ask us to keep the messages encrypted in our database.

2021-01-16 14:56 UTC, eridincu approved these changes

2021-01-16 16:26 UTC, multiminparvo approved these changes

2021-01-16 16:29 UTC, olcaytoturker approved these changes

2021-01-19 15:18 UTC, merged